<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('users')->truncate();
		DB::table('users')->insert([
			[
				'role' => 1,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 1,
				'last_name' => '鈴木',
				'first_name' => '太郎',
				'email' => 's-taro@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2010-07-01',
				'base_date' => '2011-01-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 2,
				'last_name' => '佐藤',
				'first_name' => '蓮',
				'email' => 's-ren@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2012-02-15',
				'base_date' => '2012-08-15',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 2,
				'department' => 50,
				'last_name' => '高橋',
				'first_name' => '翔',
				'email' => 't-sho@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2012-06-10',
				'base_date' => '2012-12-10',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 50,
				'department' => 0,
				'last_name' => '田中',
				'first_name' => 'さくら',
				'email' => 't-sakura@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2014-10-01',
				'base_date' => '2015-04-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 1,
				'last_name' => '伊藤',
				'first_name' => '菫',
				'email' => 'i-sumire@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2014-02-05',
				'base_date' => '2014-08-05',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 2,
				'last_name' => '山本',
				'first_name' => '椿',
				'email' => 'y-tsubaki@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2013-08-12',
				'base_date' => '2014-02-12',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 99,
				'type_of_employment' => 2,
				'department' => 50,
				'last_name' => '中村',
				'first_name' => '大樹',
				'email' => 'n-daiki@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2012-05-21',
				'base_date' => '2012-11-21',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 0,
				'last_name' => '加藤',
				'first_name' => '健太',
				'email' => 'k-kenta@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2010-04-01',
				'base_date' => '2010-10-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 50,
				'department' => 1,
				'last_name' => '吉田',
				'first_name' => 'かすみ',
				'email' => 'y-kasumi@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2011-04-01',
				'base_date' => '2011-10-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 2,
				'last_name' => '山田',
				'first_name' => 'ゆり',
				'email' => 'y-yuri@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2010-07-01',
				'base_date' => '2011-01-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 50,
				'last_name' => '佐々木',
				'first_name' => '菊',
				'email' => 's-kiku@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2016-08-01',
				'base_date' => '2017-02-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 2,
				'department' => 2,
				'last_name' => '山口',
				'first_name' => 'さくら',
				'email' => 'y-sakura@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2016-10-17',
				'base_date' => '2016-04-17',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 99,
				'type_of_employment' => 1,
				'department' => 2,
				'last_name' => '松本',
				'first_name' => '柊',
				'email' => 'm-hiiragi@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2016-01-11',
				'base_date' => '2016-07-11',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 1,
				'last_name' => '井上',
				'first_name' => '梅',
				'email' => 'i-ume@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2011-06-15',
				'base_date' => '2011-12-15',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 2,
				'last_name' => '木村',
				'first_name' => '優斗',
				'email' => 'k-yuto@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2012-03-19',
				'base_date' => '2012-09-19',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 1,
				'last_name' => '林',
				'first_name' => '亮',
				'email' => 'h-ryo@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2013-05-01',
				'base_date' => '2013-11-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
			[
				'role' => 20,
				'status' => 1,
				'type_of_employment' => 1,
				'department' => 1,
				'last_name' => '斎藤',
				'first_name' => '和也',
				'email' => 's-kazuya@gmail.com',
				'password' => bcrypt('aaaaaaaa'),
				'date_of_entering' => '2009-07-01',
				'base_date' => '2010-01-01',
				'memo' => '備考備考備考備考',
				'created_at' => Carbon\Carbon::now(),
				'updated_at' => Carbon\Carbon::now(),
			],
		]);
	}

}
